joint_ids_map: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28]
step_dt: 0.02
stiffness: [40.2, 99.1, 40.2, 99.1, 28.5, 28.5,
            40.2, 99.1, 40.2, 99.1, 28.5, 28.5,
            40.2, 28.5, 28.5,
            14.3, 14.3, 14.3, 14.3, 14.3, 16.8, 16.8,
            14.3, 14.3, 14.3, 14.3, 14.3, 16.8, 16.8]
damping:   [2.6, 6.3, 2.6, 6.3, 1.8, 1.8,
            2.6, 6.3, 2.6, 6.3, 1.8, 1.8,
            2.6, 1.8, 1.8,
            0.9, 0.9, 0.9, 0.9, 0.9, 1.1, 1.1,
            0.9, 0.9, 0.9, 0.9, 0.9, 1.1, 1.1]
default_joint_pos: [-0.312, 0, 0, 0.669, -0.363, 0,
                    -0.312, 0, 0, 0.669, -0.363, 0,
                    0, 0, 0,
                    0.2, 0.2, 0, 0.6, 0, 0, 0,
                    0.2, -0.2, 0, 0.6, 0, 0, 0]

commands:
  base_velocity:
    ranges:
      lin_vel_x: [0.0, 0.0]
      lin_vel_y: [0.0, 0.0]
      ang_vel_z: [0.0, 0.0]
      heading: null

actions:
  JointPositionAction:
    clip: null
    joint_names: [.*]
    scale: [0.548, 0.351, 0.548, 0.351, 0.439, 0.439,
            0.548, 0.351, 0.548, 0.351, 0.439, 0.439,
            0.548, 0.439, 0.439,
            0.439, 0.439, 0.439, 0.439, 0.439, 0.075, 0.075,
            0.439, 0.439, 0.439, 0.439, 0.439, 0.075, 0.075]
    offset: [-0.312, 0, 0, 0.669, -0.363, 0,
             -0.312, 0, 0, 0.669, -0.363, 0,
             0, 0, 0,
             0.2, 0.2, 0, 0.6, 0, 0, 0,
             0.2, -0.2, 0, 0.6, 0, 0, 0]
    joint_ids: null

observations:
  base_ang_vel:
    params: {}
    clip: null
    scale: [1.0, 1.0, 1.0]
    history_length: 1
  projected_gravity:
    params: {}
    clip: null
    scale: [1.0, 1.0, 1.0]
    history_length: 1
  joint_pos_rel:
    params: {}
    clip: null
    scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
            1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    history_length: 1
  joint_vel_rel:
    params: {}
    clip: null
    scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
            1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    history_length: 1
  last_action:
    params: {}
    clip: null
    scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
            1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    history_length: 1
  velocity_commands:
    params: {command_name: base_velocity}
    clip: null
    scale: [1.0, 1.0, 1.0]
    history_length: 1
  joint_pos_command:
    params:
      default_values: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    clip: null
    scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    history_length: 1
  stiffness_command:
    params:
      value: 40.0
    clip: null
    scale: [1.0]
    history_length: 1
